/* hexdecode.c: transform the data file generated by hexencode. the data file must begin with "begin NAME" */
#include <stdio.h>
#include <strings.h>
#define BUFSIZE 1024

main(int argc, char **argv)
{
	unsigned char c;
	char buf[BUFSIZE];
	char *name;
	char *newline;
	FILE *f;

	if(fgets(buf, sizeof(buf), stdin)==NULL){
		fprintf(stderr, "%s: read error or reach EOF.\n", argv[0]);
		exit(1);
	}
	
	name=buf+6; 
	if((newline=strchr(name, '\n')) != NULL) /* cut the newline in name*/
		*newline='\0';	
	f=fopen(name, "w+b");	
	while(scanf("%02x",&c) != EOF)
		fputc(c, f);

return 0;
}

	
			
